In [2]:
import pandas as pd

In [3]:
connections = pd.read_csv('connections_princeton.csv.gz')
connections

                pre_root_id        post_root_id neuropil  syn_count nt_type
0        720575940625363947  720575940623224444     ME_L         12    GABA
1        720575940630432382  720575940618518557     ME_L         67     ACH
2        720575940627314521  720575940626337738     ME_L         10    GABA
3        720575940620280405  720575940620204726     ME_L         15     ACH
4        720575940636942447  720575940613789411     LA_L          1    GLUT
...                     ...                 ...      ...        ...     ...
5342441  720575940610739918  720575940617129885    PLP_L          5     ACH
5342442  720575940653332385  720575940623905719    CRE_R          2     ACH
5342443  720575940622485887  720575940631031803     ME_R          9     ACH
5342444  720575940620020534  720575940636489140    SMP_L          2     ACH
5342445  720575940632648612  720575940626847765      GNG         19    GABA

[5342446 rows x 5 columns]

In [4]:
baker_cells = pd.read_csv('Auditory neurons Lockwood et al 2026 - Sheet1.csv')
baker_cells

,Neuron name (Lockwood et al),Cell type (Lockwood et al),Coordinates,Codex June 2024,HB type,NT2026 (FAFB and BANC),layer_mean,Across-hemi_layer_mean
0,A1_R1,A1,[160548 55409 4977],720575940631693610,AMMC-A1,inconclusive,3.823718,3.896368
1,A1_R2,A1,[161229 56723 4921],720575940631200327,AMMC-A1,inconclusive,4.294872,NaN
2,A1_R3,A1,[159857 56701 5018],720575940618522433,AMMC-A1,inconclusive,3.730769,NaN
3,A1_L1,A1,[105496 54286 5405],720575940612001489,AMMC-A1,inconclusive,3.746795,NaN
4,A1_L2,A1,[105654 55604 5474],720575940616313942,AMMC-A1,inconclusive,3.939103,NaN
...,...,...,...,...,...,...,...,...
901,JO-B_L162,JO-B,NaN,720575940631670584,NaN,Ach,NaN,NaN
902,JO-B_L163,JO-B,NaN,720575940617244049,NaN,Ach,NaN,NaN
903,JO-B_L164,JO-B,NaN,720575940617407929,NaN,Ach,NaN,NaN
904,JO-B_L165,JO-B,NaN,720575940620257216,NaN,Ach,NaN,NaN
905,JO-B_L166,JO-B,NaN,720575940614805983,NaN,Ach,NaN,NaN

In [5]:
celltypes = baker_cells[['Cell type (Lockwood et al)', 'Codex June 2024', 'NT2026 (FAFB and BANC)', 'layer_mean', 'Across-hemi_layer_mean']]
celltypes

,Cell type (Lockwood et al),Codex June 2024,NT2026 (FAFB and BANC),layer_mean,Across-hemi_layer_mean
0,A1,720575940631693610,inconclusive,3.823718,3.896368
1,A1,720575940631200327,inconclusive,4.294872,NaN
2,A1,720575940618522433,inconclusive,3.730769,NaN
3,A1,720575940612001489,inconclusive,3.746795,NaN
4,A1,720575940616313942,inconclusive,3.939103,NaN
...,...,...,...,...,...
901,JO-B,720575940631670584,Ach,NaN,NaN
902,JO-B,720575940617244049,Ach,NaN,NaN
903,JO-B,720575940617407929,Ach,NaN,NaN
904,JO-B,720575940620257216,Ach,NaN,NaN
905,JO-B,720575940614805983,Ach,NaN,NaN

In [6]:
lockwood_ids = celltypes['Codex June 2024']
connections_filtered = connections[(connections['pre_root_id'].isin(lockwood_ids)) & (connections['post_root_id'].isin(lockwood_ids))]
connections_filtered

                pre_root_id        post_root_id neuropil  syn_count nt_type
100421   720575940644968302  720575940612975853   AVLP_L         29     ACH
104142   720575940627174247  720575940603683505   AVLP_L         27     ACH
105947   720575940621447077  720575940627827450   AVLP_L         26     ACH
113109   720575940632649697  720575940603186790   AVLP_L         54     ACH
113363   720575940630744019  720575940603683505   AVLP_L         22     ACH
...                     ...                 ...      ...        ...     ...
5341841  720575940631425965  720575940622123981    WED_L          3    GABA
5342044  720575940630223052  720575940623322877   AVLP_L         43     ACH
5342264  720575940614332899  720575940644968302      SAD          2     ACH
5342355  720575940619508033  720575940644488727      SAD         14     ACH
5342438  720575940634829168  720575940646518382    VES_L          8     ACH

[19528 rows x 5 columns]

In [7]:
firstmerge = connections_filtered.merge(celltypes, how='left', left_on='pre_root_id', right_on='Codex June 2024').drop(columns=['Codex June 2024']).rename(columns={'Cell type (Lockwood et al)':'type_pre'})
conns = firstmerge.merge(celltypes, how='left', left_on='post_root_id', right_on='Codex June 2024').drop(columns=['Codex June 2024']).rename(columns={'Cell type (Lockwood et al)':'type_post'})
conns = conns.rename(columns={'NT2026 (FAFB and BANC)_x':'nt_type_banc', 'layer_mean_x':'layer_mean_pre', 'Across-hemi_layer_mean_x':'across_hemi_layer_pre', 'layer_mean_y':'layer_mean_post', 'Across-hemi_layer_mean_y':'across_hemi_layer_post'}).drop(columns=['NT2026 (FAFB and BANC)_y'])
conns = conns[['pre_root_id', 'post_root_id', 'syn_count', 'nt_type_banc', 'type_pre', 'type_post', 'layer_mean_pre', 'layer_mean_post', 'across_hemi_layer_pre', 'across_hemi_layer_post']]
conns

,pre_root_id,post_root_id,syn_count,nt_type_banc,type_pre,type_post,layer_mean_pre,layer_mean_post,across_hemi_layer_pre,across_hemi_layer_post
0,720575940644968302,720575940612975853,29,Ach,AVLP_pr23,AVLP/PVLP_pr01-2,3.144231,4.358974,3.192308,NaN
1,720575940627174247,720575940603683505,27,Ach,WED-VLP-1,AVLP_pr01-2,3.310897,4.070513,NaN,NaN
2,720575940621447077,720575940627827450,26,Ach,WED-VLP-1,AVLP_pr31,3.224359,4.352564,NaN,NaN
3,720575940632649697,720575940603186790,54,Ach,A2,WED-VLP-1,2.317308,3.314103,NaN,NaN
4,720575940630744019,720575940603683505,22,Ach,WED-VLP-2,AVLP_pr01-2,3.423077,4.070513,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
19523,720575940631425965,720575940622123981,3,GABA,AVLP_pr01-1,WV-WV-1,2.621795,2.326923,NaN,NaN
19524,720575940630223052,720575940623322877,43,Ach,B1-1,WV-WV-1,2.169872,3.176282,NaN,2.711538
19525,720575940614332899,720575940644968302,2,Ach,JO-A,AVLP_pr23,NaN,3.144231,NaN,3.192308
19526,720575940619508033,720575940644488727,14,Ach,JO-A,SAD_pr01,NaN,2.320513,NaN,NaN
19527,720575940634829168,720575940646518382,8,Ach,vpoEN,pC1d,3.740385,5.891026,NaN,NaN

In [8]:
g_all = conns.copy().rename(columns={'pre_root_id':'Source', 'post_root_id':'Target', 'syn_count':'Weight'})

In [9]:
g_all.to_csv('g_all.csv', index=False)

In [10]:
celltypes

,Cell type (Lockwood et al),Codex June 2024,NT2026 (FAFB and BANC),layer_mean,Across-hemi_layer_mean
0,A1,720575940631693610,inconclusive,3.823718,3.896368
1,A1,720575940631200327,inconclusive,4.294872,NaN
2,A1,720575940618522433,inconclusive,3.730769,NaN
3,A1,720575940612001489,inconclusive,3.746795,NaN
4,A1,720575940616313942,inconclusive,3.939103,NaN
...,...,...,...,...,...
901,JO-B,720575940631670584,Ach,NaN,NaN
902,JO-B,720575940617244049,Ach,NaN,NaN
903,JO-B,720575940617407929,Ach,NaN,NaN
904,JO-B,720575940620257216,Ach,NaN,NaN
905,JO-B,720575940614805983,Ach,NaN,NaN

In [11]:
g_all_nodelist = celltypes.copy()
g_all_nodelist = g_all_nodelist.rename(columns={'Codex June 2024':'Id', 'Cell type (Lockwood et al)':'Label', 'layer_mean':'layer_mean[z]'})
g_all_nodelist = g_all_nodelist[['Id', 'Label', 'NT2026 (FAFB and BANC)', 'layer_mean[z]', 'Across-hemi_layer_mean']]
g_all_nodelist

,Id,Label,NT2026 (FAFB and BANC),layer_mean[z],Across-hemi_layer_mean
0,720575940631693610,A1,inconclusive,3.823718,3.896368
1,720575940631200327,A1,inconclusive,4.294872,NaN
2,720575940618522433,A1,inconclusive,3.730769,NaN
3,720575940612001489,A1,inconclusive,3.746795,NaN
4,720575940616313942,A1,inconclusive,3.939103,NaN
...,...,...,...,...,...
901,720575940631670584,JO-B,Ach,NaN,NaN
902,720575940617244049,JO-B,Ach,NaN,NaN
903,720575940617407929,JO-B,Ach,NaN,NaN
904,720575940620257216,JO-B,Ach,NaN,NaN
905,720575940614805983,JO-B,Ach,NaN,NaN

In [12]:
g_all_nodelist.to_csv('g_all_nodelist.csv', index=False)

In [13]:
conns_bytype = conns.groupby(['type_pre', 'type_post', 'nt_type_banc'], as_index=False)[['syn_count']].sum().sort_values(by='syn_count', ascending=False)
conns_bytype

        type_pre         type_post  nt_type_banc  syn_count
191         B1-5          WED_pr02           Ach       6248
155         B1-3          WED_pr02           Ach       5537
279         JO-A                A2           Ach       4753
141         B1-2          WED_pr02           Ach       4316
121         B1-1         WED-VLP-1           Ach       3640
..           ...               ...           ...        ...
254           GF  AVLP/PVLP_pr01-2  Inconclusive          5
525         pMN1             pC2lb           Ach          5
70     AVLP_pr12              pC1d           Ach          5
72   AVLP_pr18-1       AVLP_pr18-2  Inconclusive          5
562      vpoIN-3             vpoEN          GABA          5

[563 rows x 4 columns]

In [14]:
g1 = conns_bytype.rename(columns={'type_pre':'Source', 'type_post':'Target', 'syn_count':'Weight'})
g1

          Source            Target  nt_type_banc  Weight
191         B1-5          WED_pr02           Ach    6248
155         B1-3          WED_pr02           Ach    5537
279         JO-A                A2           Ach    4753
141         B1-2          WED_pr02           Ach    4316
121         B1-1         WED-VLP-1           Ach    3640
..           ...               ...           ...     ...
254           GF  AVLP/PVLP_pr01-2  Inconclusive       5
525         pMN1             pC2lb           Ach       5
70     AVLP_pr12              pC1d           Ach       5
72   AVLP_pr18-1       AVLP_pr18-2  Inconclusive       5
562      vpoIN-3             vpoEN          GABA       5

[563 rows x 4 columns]

In [15]:
g2 = conns.groupby(['type_pre', 'type_post', 'nt_type_banc', 'layer_mean_pre', 'layer_mean_post'], as_index=False)[['syn_count']].sum().sort_values(by='syn_count', ascending=False)
g2 = g2.rename(columns={'type_pre':'Source', 'type_post':'Target', 'syn_count':'Weight'})
g2

        Source    Target nt_type_banc  layer_mean_pre  layer_mean_post  Weight
2086      B1-5  WED_pr02          Ach        2.573718         3.516026     287
1518      B1-3  WED_pr02          Ach        2.509615         3.378205     285
4200   WV-WV-1  WED_pr02         GABA        3.176282         3.445513     279
4432   WV-WV-3        GF         GABA        2.410256         3.179487     273
2119      B1-5  WED_pr02          Ach        3.051282         3.564103     271
...        ...       ...          ...             ...              ...     ...
4462   WV-WV-3   WV-WV-1         GABA        2.846154         2.326923       5
1114      B1-2      B1-2          Ach        2.663462         2.387821       5
4464   WV-WV-3   WV-WV-2         GABA        2.535256         3.355769       5
3666  WED_pr02        GF         GABA        3.128205         3.467949       5
5128   vpoIN-3     vpoEN         GABA        3.916667         3.641026       5

[5129 rows x 6 columns]

In [16]:
g2.to_csv('g2.csv', index=False)

In [17]:
g3 = conns.groupby(['type_pre', 'type_post', 'nt_type_banc', 'across_hemi_layer_pre', 'across_hemi_layer_post'], as_index=False, dropna=False)[['syn_count']].sum().sort_values(by=['syn_count'], ascending=False)
g3 = g3.rename(columns={'type_pre':'Source', 'type_post':'Target', 'syn_count':'Weight'})
g3 = g3[['Source', 'Target', 'Weight', 'nt_type_banc', 'across_hemi_layer_pre', 'across_hemi_layer_post']]
g3

,Source,Target,Weight,nt_type_banc,across_hemi_layer_pre,across_hemi_layer_post
395,B1-5,WED_pr02,5282,Ach,NaN,NaN
312,B1-3,WED_pr02,4964,Ach,NaN,NaN
283,B1-2,WED_pr02,3960,Ach,NaN,NaN
562,JO-A,A2,3567,Ach,NaN,NaN
589,JO-A,WV-WV-3,3178,Ach,NaN,NaN
...,...,...,...,...,...,...
650,SAD_pr01,A1,5,GABA,NaN,NaN
657,SAD_pr01,B1-3,5,GABA,2.352564,NaN
667,SAD_pr02,AVLP_pr23,5,GABA,NaN,NaN
668,SAD_pr02,B1-1,5,GABA,NaN,NaN
1120,vpoIN-3,vpoEN,5,GABA,3.921474,3.688301

In [18]:
g3.to_csv('g3.csv', index=False)

In [19]:
g3_nodelist = celltypes.copy()
g3_nodelist = g3_nodelist.groupby(['Cell type (Lockwood et al)', 'NT2026 (FAFB and BANC)'], as_index=False)[['Across-hemi_layer_mean']].mean()
g3_nodelist = g3_nodelist.rename(columns={'Cell type (Lockwood et al)':'Id', 'NT2026 (FAFB and BANC)':'nt_type_banc', 'Across-hemi_layer_mean':'layer[z]'})
g3_nodelist

                  Id  nt_type_banc  layer[z]
0                 A1  inconclusive  3.896368
1                 A2           Ach  2.304487
2   AVLP/PVLP_pr01-1           Ach  6.126603
3   AVLP/PVLP_pr01-2           Ach  4.173077
4        AVLP_pr01-1          GABA  2.782372
..               ...           ...       ...
65            pcC2lc           Ach       NaN
66             vpoEN           Ach  3.688301
67           vpoIN-1          GABA  5.360897
68           vpoIN-2          GABA  5.345620
69           vpoIN-3          GABA  3.921474

[70 rows x 3 columns]

In [20]:
g3_nodelist.to_csv('g3_nodelist.csv', index=False)

In [21]:
celltypes[['Cell type (Lockwood et al)']].drop_duplicates() #make sure we didn't lose any cell types in process of making nodelist

    Cell type (Lockwood et al)
0                           A1
5                           A2
9                         B1-1
22                        B1-2
38                        B1-3
..                         ...
490                       pC1e
492                       aPN3
502                       aPN2
513                       JO-A
607                       JO-B

[70 rows x 1 columns]

In [22]:
mode_prefs = pd.read_csv('train_dat.csv')
mode_prefs

,Unnamed: 0,Flywire 2024 ID,Neuropils,preference,# imaged females,# responding females,prop females with auditory responses
0,0,720575940619783518,AVLP_pr01,sine,4,4,1.000000
1,1,720575940620062633,AVLP_pr01,sine,4,4,1.000000
2,2,720575940602914988,AVLP_pr01,sine,4,4,1.000000
3,3,720575940620195719,AVLP_pr01,sine,4,4,1.000000
4,4,720575940634508174,AVLP_pr01,sine,4,4,1.000000
...,...,...,...,...,...,...,...
398,398,720575940655398817,GNG_pr01,sine,17,4,0.235294
399,399,720575940630203589,GNG_pr01,sine,17,4,0.235294
400,400,720575940617641077,GNG_pr01,sine,17,4,0.235294
401,401,720575940612801022,GNG_pr01,sine,17,4,0.235294
402,402,720575940630571068,GNG_pr01,sine,17,4,0.235294

In [30]:
modeprefspre = conns.merge(mode_prefs, how='left', left_on='pre_root_id', right_on='Flywire 2024 ID').drop(columns=['Unnamed: 0', 'Flywire 2024 ID', 'Neuropils', '# imaged females', '# responding females', 'prop females with auditory responses']).rename(columns={'preference':'pref_pre'})
conns_withprefs = modeprefspre.merge(mode_prefs, how='left', left_on='post_root_id', right_on='Flywire 2024 ID').drop(columns=['Unnamed: 0', 'Flywire 2024 ID', 'Neuropils', '# imaged females', '# responding females', 'prop females with auditory responses']).rename(columns={'preference':'pref_post'})
conns_withprefs

,pre_root_id,post_root_id,syn_count,nt_type_banc,type_pre,type_post,layer_mean_pre,layer_mean_post,across_hemi_layer_pre,across_hemi_layer_post,pref_pre,pref_post
0,720575940644968302,720575940612975853,29,Ach,AVLP_pr23,AVLP/PVLP_pr01-2,3.144231,4.358974,3.192308,NaN,intermediate,pulse
1,720575940627174247,720575940603683505,27,Ach,WED-VLP-1,AVLP_pr01-2,3.310897,4.070513,NaN,NaN,intermediate,sine
2,720575940621447077,720575940627827450,26,Ach,WED-VLP-1,AVLP_pr31,3.224359,4.352564,NaN,NaN,intermediate,sine
3,720575940632649697,720575940603186790,54,Ach,A2,WED-VLP-1,2.317308,3.314103,NaN,NaN,pulse,intermediate
4,720575940630744019,720575940603683505,22,Ach,WED-VLP-2,AVLP_pr01-2,3.423077,4.070513,NaN,NaN,intermediate,sine
...,...,...,...,...,...,...,...,...,...,...,...,...
19523,720575940631425965,720575940622123981,3,GABA,AVLP_pr01-1,WV-WV-1,2.621795,2.326923,NaN,NaN,sine,NaN
19524,720575940630223052,720575940623322877,43,Ach,B1-1,WV-WV-1,2.169872,3.176282,NaN,2.711538,pulse,NaN
19525,720575940614332899,720575940644968302,2,Ach,JO-A,AVLP_pr23,NaN,3.144231,NaN,3.192308,NaN,intermediate
19526,720575940619508033,720575940644488727,14,Ach,JO-A,SAD_pr01,NaN,2.320513,NaN,NaN,NaN,NaN
19527,720575940634829168,720575940646518382,8,Ach,vpoEN,pC1d,3.740385,5.891026,NaN,NaN,NaN,NaN